### ISSUE TITLE
Parsing error on Samsung 2019 (TIZEN 5.0)

### ISSUE THREAD

**Issue by michlq** [OneLiberty/moonlight-chrome-tizen#3]
Hi OneLiberty. 
Is there a way to install moonlight on a TIZEN system before version 5.5?

The error occurs:
package_path /home/owner/share/tmp/sdk_tools/tmp/MoonlightWasm.wgt
was_install_app return WAS_TRUE
app_id[MoonLightS.MoonlightWasm] install start
app_id[MoonLightS.MoonlightWasm] install failed[118, -19], reason: Parsing error :
spend time for wascmd is [746]ms
cmd_ret:0
Failed to install Tizen application.

The trick of changing the config file doesn't help.
The app is then installed, but the plugin on the TV does not load.

Maybe you have an idea to get it running?

Since Steam Link will unfortunately be discontinued for Samsung at the end of 2023 (at least for 2019 devices), it would be really great to have a useful alternative without having to buy a box.

best regards

**Comment by OneLiberty** [comment]
This is because your tizen version is (unfortunatly) not compatible with WebAssembly (which is the base of this port)

>Is there a way to install moonlight on a TIZEN system before version 5.5?

Yes but it still won't work. 
For now, you're stuck with nothing. 

> Maybe you have an idea to get it running?

The only way you could get something, is by adapting the current [moonlight-chrome](https://github.com/moonlight-stream/moonlight-chrome) (which is running NaCl, that should be, at least for the most part, compatible with tizen 5.0 or lower) 

I tried to look at it, but i can't create a project for 5.0 or lower on tizen studio, and i don't really know why, i'll be looking into it when i have time, but for now my main focus is this WASM app. 
Also, i don't have tizen 5.0/lower hardware available, so i have to use emulator which isn't the best for testing...

**Comment by michlq** [comment]
> This is because your tizen version is (unfortunatly) not compatible with WebAssembly (which is the base of this port)
> 
> > Is there a way to install moonlight on a TIZEN system before version 5.5?
> 
> Yes but it still won't work. For now, you're stuck with nothing.
> 
> > Maybe you have an idea to get it running?
> 
> The only way you could get something, is by adapting the current [moonlight-chrome](https://github.com/moonlight-stream/moonlight-chrome) (which is running NaCl, that should be, at least for the most part, compatible with tizen 5.0 or lower)
> 
> I tried to look at it, but i can't create a project for 5.0 or lower on tizen studio, and i don't really know why, i'll be looking into it when i have time, but for now my main focus is this WASM app. Also, i don't have tizen 5.0/lower hardware available, so i have to use emulator which isn't the best for testing...

Thank you for your quick response.
Then I hope that you might find the time to take a look. but don't stress yourself out.

**Comment by OneLiberty** [comment]
>Thank you for your quick response.

No problem. 
Honnestly, i know next to nothing about app development, i'm just stuppidly determined to improve this app. 
I wouldn't count on me ^^'

I'm closing the issue since it isn't really fixable
